### ISSUE TITLE
couldn't determine 32/64 bit of java

### ISSUE THREAD

**Issue by FunsKiTo** [indifferentbroccoli/projectzomboid-server-docker#19]
## Describe the bug

Server is not starting, the java files are in the folder with the right permissions but it gives me the error: "couldn't determine 32/64 bit of java"

## To Reproduce

Run the server

## Expected behavior

Server start

## Actual behavior

Server not starting

## OS information (IMPORTANT)

- OS:  Debian
- Docker Image Version:  Main

## Hardware information (IMPORTANT)

- CPU:  AMD Ryzen 3 3100
- Memory:  32GB ddr4

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
services:
  projectzomboid:
    image: indifferentbroccoli/projectzomboid-server-docker
    restart: unless-stopped
    container_name: projectzomboid
    stop_grace_period: 30s
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
      - 27015:27015/tcp
    environment:
      GENERATE_SETTINGS: true
    env_file:
      - .env
    volumes:
      - /srv/6fa7399c-5518-4bcc-a7c0-97f29162fb9c/BackUp/projectzomboid/server-files:/project-zomboid
      - /srv/6fa7399c-5518-4bcc-a7c0-97f29162fb9c/BackUp/projectzomboid/server-data:/project-zomboid-config
```

</details>

## Container/Host Logs (IMPORTANT)

<details><summary>Logs</summary>

```log
====Starting server====
projectzomboid  | ./start-server.sh: line 26:   435 Segmentation fault      (core dumped) "${INSTDIR}/jre64/bin/java" -version > /dev/null 2>&1
projectzomboid  | couldn't determine 32/64 bit of java
```

</details>

## Bug Report Checklist

- [x] I searched for my issue in the [Closed issues](https://github.com/indifferentbroccoli/projectzomboid-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have included all relevant information required above.
- [x] I am willing to fix this bug
